// <auto-generated />
using System;
using Helpdesk.Data.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Web.Mvc.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Helpdesk.Model.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine");

                    b.Property<string>("Country");

                    b.Property<string>("District");

                    b.Property<string>("PostCode");

                    b.Property<string>("Province");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AccountId");

                    b.Property<int?>("AddressId");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(128);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("FixedNumber");

                    b.Property<string>("LastName");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Title");

                    b.Property<string>("TrIdentityNumber");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.ApplicationUserRoleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationUserId");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(128);

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("ApplicationUserRoleMapping");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(128);

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("UserLimit");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.CompanyAgentMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationUserId");

                    b.Property<int>("CompanyId");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(128);

                    b.Property<bool>("IsSpecifiedForCompany");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("CompanyAgentMapping");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.CompanyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AccountId");

                    b.Property<int?>("AddressId");

                    b.Property<int>("CompanyId");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(128);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("FixedNumber");

                    b.Property<string>("LastName");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Title");

                    b.Property<string>("TrIdentityNumber");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyUser");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.CompanyUserRoleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyUserId");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(128);

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("CompanyUserRoleMapping");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.Demand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("ApplicationUserAccountId");

                    b.Property<int>("CompanyId");

                    b.Property<Guid>("CompanyUserAccountId");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(128);

                    b.Property<bool>("IsAccepted");

                    b.Property<bool>("IsCompleted");

                    b.Property<bool>("IsDissolved");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int>("OrderOfUrgencyId");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Text")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("Demands");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.OrderOfUrgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(128);

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("OrderOfUrgency");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Helpdesk.Model.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("Helpdesk.Model.Entities.CompanyUser", b =>
                {
                    b.HasOne("Helpdesk.Model.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Helpdesk.Model.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
